name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['8.2', '8.3', '8.4']

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-version }}

    - name: Set up git credentials
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global credential.helper store
        echo "https://${{ secrets.TOKEN }}:x-oauth-basic@github.com" > ~/.git-credentials

    - name: Install dependencies
      run: composer install

    - name: Run tests
      run: ./vendor/bin/pest
